### PR TITLE
11 error on scroll button position

### LINKED ISSUE #11: Error on scroll button position
The scroll button breaks on pages.

<hr>

image

image

image

### PR DESCRIPTION
**Pull request by RayzaOliveira**
Fixes #11 #12 #14

### CODE REVIEW

**Comment by arantespp** [comment]
@enniolopes, could you review this PR?

**Comment by enniolopes** [comment]
We need some adjustments on these pages:

<hr>

image

image

**Comment by arantespp** [comment]
@RayzaOliveira, could you check this problem, please? I think we can decrease the feature card height or width on this responsivity.

image

**Comment by arantespp** [comment]
@enniolopes could you check again, please?

**Comment by enniolopes** [comment]
> 
> 
> @enniolopes could you check again, please?

the error remains the same

**Comment by arantespp** [comment]
@enniolopes considering height equals 632px, the Features page is working here with the width between 1024 and 1535px. What is the size of your screen?

image

**Comment by enniolopes** [comment]
> 
> 
> @enniolopes considering height equals 632px, the Features page is working here with the width between 1024 and 1535px. What is the size of your screen?
> 

ok, you can merge.
here the browser vh is 888px

**Comment by arantespp** [comment]
@enniolopes send a print. Maybe aren't you with some zoom in your browser?

**Review by arantespp — APPROVED** [review]

**Pull request merged**
